### ISSUE TITLE
Invalid router info

### ISSUE THREAD

**Issue by jeffpkamp** [ofekp/TinyUPnP#13] opened 2018-06-17 04:39 UTC
Trying this out on the esp8266 and I get the "Invalid router info, cannot continue" message when I give it a time out.   Looking at the source code, there are three conditions that lead to this but I'm not sure which one is mine.  below is the output from the program.  UPnP is enabled because I can get it to work with pythons miniUPnP.
```
Connected to network
IP address: 192.168.0.122
Sending M-SEARCH to [4211081199] Port [1900]
M-SEARCH sent
Received packet of size [260] ip [192.168.0.1] port [1900]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=100
DATE: Sat, 16 Jun 2018 22:32:09 GMT
EXT:
LOCATION: http://192.168.0.1:1900/igd.xml
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
ST: upnp:rootdevice
USN: uuid:060b7353-fca6-4070-85f4-1fbfb9add62c::upnp:rootdevic
Received packet of size [269] ip [192.168.0.1] port [1900]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=100
DATE: Sat, 16 Jun 2018 22:32:09 GMT
EXT:

LOCATION: http://192.168.0.1:1900/igd.xml
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
ST: uuid:060b7353-fca6-4070-85f4-1fbfb9add62c
USN: uuid:060b7353-fca6-4070-85f4-1f
Received packet of size [332] ip [192.168.0.1] port [1900]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=100
DATE: Sat, 16 Jun 2018 22:32:09 GMT
EXT:
LOCATION: http://192.168.0.1:1900/igd.xml
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
USN: uuid:060b7353-fca6-40
Received packet of size [324] ip [192.168.0.1] port [1900]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=100
DATE: Sat, 16 Jun 2018 22:32:09 GMT
EXT:
LOCATION: http://192.168.0.1:1900/igd.xml
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
ST: urn:schemas-upnp-org:service:Layer3Forwarding:1
USN: uuid:060b7353-fca6-4070-8
Received packet of size [269] ip [192.168.0.1] port [1900]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=100
DATE: Sat, 16 Jun 2018 22:32:10 GMT
EXT:
LOCATION: http://192.168.0.1:1900/igd.xml
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
ST: uuid:254e9977-8964-49f3-b8d5-51acb7bd40fc
USN: uuid:254e9977-8964-49f3-b8d5-51
Received packet of size [308] ip [192.168.0.1] port [1900]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=100
DATE: Sat, 16 Jun 2018 22:32:10 GMT
EXT:
LOCATION: http://192.168.0.1:1900/igd.xml
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
ST: urn:schemas-upnp-org:device:WANDevice:1
USN: uuid:254e9977-8964-49f3-b8d5-51ac
Received packet of size [340] ip [192.168.0.1] port [1900]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=100
DATE: Sat, 16 Jun 2018 22:32:10 GMT
EXT:

OCATION: http://192.168.0.1:1900/igd.xml
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
ST: uuid:9f0865b3-f5da-4ad5-85b7-7404637fdf37
USN: uuid:9f0865b3-f5da-4ad5-85b7-74
Received packet of size [328] ip [192.168.0.1] port [1900]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=100
DATE: Sat, 16 Jun 2018 22:32:10 GMT
EXT:
LOCATION: http://192.168.0.1:1900/igd.xml
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
ST: urn:schemas-upnp-org:device:WANConnectionDevice:1
USN: uuid:9f0865b3-f5da-4ad5
Received packet of size [322] ip [192.168.0.1] port [1900]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=100
DATE: Sat, 16 Jun 2018 22:32:10 GMT
EXT:
LOCATION: http://192.168.0.1:1900/igd.xml
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
ST: urn:schemas-upnp-org:service:WANIPConnection:1
USN: uuid:9f0865b3-f5da-4ad5-85
Received packet of size [269] ip [192.168.0.1] port [1900]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=100
DATE: Sat, 16 Jun 2018 22:32:10 GMT
EXT:
LOCATION: http://192.168.0.1:1900/igd.xml
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
ST: uuid:565aa949-67c1-4c0e-aa8f-f349e6f59311
USN: uuid:565aa949-67c1-4c0e-aa8f-f3
Received packet of size [324] ip [192.168.0.1] port [1900]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=100
DATE: Sat, 16 Jun 2018 22:32:10 GMT
EXT:
LOCATION: http://192.168.0.1:1900/igd.xml
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
ST: urn:schemas-wifialliance-org:device:WFADevice:1
USN: uuid:565aa949-67c1-4c0e-a
Received packet of size [334] ip [192.168.0.1] port [1900]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=100
DATE: Sat, 16 Jun 2018 22:32:10 GMT
EXT:
LOCATION: http://192.168.0.1:1900/igd.xml
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
ST: urn:schemas-wifialliance-org:service:WFAWLANConfig:1
USN: uuid:565aa949-67c1-4
Received packet of size [264] ip [192.168.0.1] port [40163]
Gateway packet content:
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.0.1:1900/igd.xml
NT: upnp:rootdevice
NTS: ssdp:alive
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
USN: uuid:060b7353-fca6-4070-85f4-1fbfb9add62c::upnp:rootd
Received packet of size [273] ip [192.168.0.1] port [40163]
Gateway packet content:
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.0.1:1900/igd.xml
NT: uuid:060b7353-fca6-4070-85f4-1fbfb9add62c
NTS: ssdp:alive
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
USN: uuid:060b7353-fca6-4070-85f
Received packet of size [336] ip [192.168.0.1] port [40163]
Gateway packet content:
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.0.1:1900/igd.xml
NT: urn:schemas-upnp-org:device:InternetGatewayDevice:1
NTS: ssdp:alive
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
USN: uuid:060b7353-fca
Received packet of size [328] ip [192.168.0.1] port [40163]
Gateway packet content:
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.0.1:1900/igd.xml
NT: urn:schemas-upnp-org:service:Layer3Forwarding:1
NTS: ssdp:alive
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
USN: uuid:060b7353-fca6-40
Received packet of size [273] ip [192.168.0.1] port [40163]
Gateway packet content:

NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.0.1:1900/igd.xml
NT: uuid:254e9977-8964-49f3-b8d5-51acb7bd40fc
NTS: ssdp:alive
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
USN: uuid:254e9977-8964-49f3-b8d
Received packet of size [312] ip [192.168.0.1] port [40163]
Gateway packet content:
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.0.1:1900/igd.xml
NT: urn:schemas-upnp-org:device:WANDevice:1
NTS: ssdp:alive
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
USN: uuid:254e9977-8964-49f3-b8d5-
Received packet of size [344] ip [192.168.0.1] port [40163]
Gateway packet content:
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.0.1:1900/igd.xml
NT: urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1
NTS: ssdp:alive
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
USN: uuid:254e9977
Received packet of size [273] ip [192.168.0.1] port [40163]
Gateway packet content:
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.0.1:1900/igd.xml
NT: uuid:9f0865b3-f5da-4ad5-85b7-7404637fdf37
NTS: ssdp:alive
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
USN: uuid:9f0865b3-f5da-4ad5-85b
Received packet of size [332] ip [192.168.0.1] port [40163]
Gateway packet content:
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.0.1:1900/igd.xml
NT: urn:schemas-upnp-org:device:WANConnectionDevice:1
NTS: ssdp:alive
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
USN: uuid:9f0865b3-f5da-
Received packet of size [326] ip [192.168.0.1] port [40163]
Gateway packet content:
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.0.1:1900/igd.xml
NT: urn:schemas-upnp-org:service:WANIPConnection:1
NTS: ssdp:alive
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
USN: uuid:9f0865b3-f5da-4ad
Received packet of size [273] ip [192.168.0.1] port [40163]
Gateway packet content:
NOTIFY * HTTP/1.1

OST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.0.1:1900/igd.xml
NT: uuid:565aa949-67c1-4c0e-aa8f-f349e6f59311
NTS: ssdp:alive
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
USN: uuid:565aa949-67c1-4c0e-aa8
Received packet of size [328] ip [192.168.0.1] port [40163]
Gateway packet content:
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.0.1:1900/igd.xml
NT: urn:schemas-wifialliance-org:device:WFADevice:1
NTS: ssdp:alive
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
USN: uuid:565aa949-67c1-4c
Received packet of size [338] ip [192.168.0.1] port [40163]
Gateway packet content:
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.0.1:1900/igd.xml
NT: urn:schemas-wifialliance-org:service:WFAWLANConfig:1
NTS: ssdp:alive
SERVER: ipos/7.0 UPnP/1.0 TL-WR841N/9.0
USN: uuid:565aa949-67
Received packet of size [272] ip [192.168.0.1] port [36961]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sat, 16 Jun 2018 22:32:13 GMT
EXT:
LOCATION: http://192.168.0.1:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: upnp:rootdevice
USN: uuid:00000000-0000-1000-0000-60e3275d7898::up
Received packet of size [272] ip [192.168.0.1] port [36961]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sat, 16 Jun 2018 22:32:13 GMT
EXT:
LOCATION: http://192.168.0.1:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: upnp:rootdevice
USN: uuid:00000000-0000-1000-0000-60e3275d7898::up
Received packet of size [281] ip [192.168.0.1] port [36961]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sat, 16 Jun 2018 22:32:13 GMT
EXT:
LOCATION: http://192.168.0.1:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: uuid:00000000-0000-1000-0000-60e3275d7898
USN: uuid:00000000-0000-
Received packet of size [281] ip [192.168.0.1] port [36961]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sat, 16 Jun 2018 22:32:13 GMT
EXT:

LOCATION: http://192.168.0.1:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: uuid:00000000-0000-1000-0000-60e3275d7898
USN: uuid:00000000-0000-
Received packet of size [336] ip [192.168.0.1] port [36961]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sat, 16 Jun 2018 22:32:13 GMT
EXT:
LOCATION: http://192.168.0.1:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: urn:schemas-wifialliance-org:device:WFADevice:1
USN: uuid:00000000
Received packet of size [336] ip [192.168.0.1] port [36961]
Gateway packet content:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Sat, 16 Jun 2018 22:32:13 GMT
EXT:
LOCATION: http://192.168.0.1:49152/wps_device.xml
SERVER: Unspecified, UPnP/1.0, Unspecified
ST: urn:schemas-wifialliance-org:device:WFADevice:1
USN: uuid:00000000

Printing Port Mappings!
Port Mappings:
Invalid router info, cannot continue

UPnP done
Gateway Address: 192.168.0.1
Network Mask: 255.255.255.0

```

**Comment by ofekp** [comment] 2018-06-18 19:58
Can you please try the code from the branch `issue10`
FYI, there is a better API soon from the branch `newApi` you can try this too if you prefer, for me it works better because of some timeouts that I changed and also fixed a few debug prints that might help us now.

In case you're interested, in the method `addPortMapping` you're stopping here https://github.com/ofekp/TinyUPnP/blob/master/src/TinyUPnP.cpp#L58

This is probably because `waitForUnicastResponseToMSearch` failed. Not sure why yet, since I do see the required `urn:schemas-upnp-org:device:InternetGatewayDevice:1` in the output you attached.
There's a chance this is related to `issue10` since the size of the packets from your router exceed 255 byte.

Anyway, let's give it a try please.
Ofek.

**Comment by jeffpkamp** [comment] 2018-06-19 23:30
I changed the UDP read length to max with no effect.  When I get the specific error it runs into during port mapping, it says it fails due to all three conditions.  Is this just an issue of it failing to parse the info from the xml file?  I tried setting the values manually when they failed (ie _gwinfo.port = 1900, _gwinfo.host = IPAddress(239,255,255,250), _gwinfo.path="http://192.168.0.1:1900/igd.xml"
, but this just times out waiting for the igd.

**Comment by jeffpkamp** [comment] 2018-06-20 00:03
The new API seems to be working.  Its a little delayed but it gets the job done in a minute or so.   I'm a little confused because it keeps cranking out information to the Serial Connection after the connection is established.  Is there a way to make it less verbose once it succeeds?

**Comment by jeffpkamp** [comment] 2018-06-21 20:30
okay, so looking at it as it runs it sort of works.  But it hangs when looking for port mapping  
```
#include <ESP8266WiFi.h>
#include <WiFiClient.h>
#include <ESP8266WebServer.h>
#include <ESP8266mDNS.h>
#include <WiFiUdp.h>
#include <ESP8266SSDP.h>
#include "TinyUPnP.h"

const char* ssid = "SSID";
const char* password = "password";
#define LISTEN_PORT 40
#define LEASE_DURATION 300  // seconds
#define FRIENDLY_NAME "test"
unsigned long lastUpdateTime = 0;

TinyUPnP *tinyUPnP = new TinyUPnP(10000);  // -1 means blocking, preferably, use a timeout value (ms)
ESP8266WebServer server(LISTEN_PORT);

void setup() {
  Serial.begin(115200);
  //WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  Serial.println("");
  // Wait for connection
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.print("Connected to ");
  Serial.println(ssid);
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());

  if (tinyUPnP->addPortMapping(WiFi.localIP(), LISTEN_PORT, RULE_PROTOCOL_TCP, LEASE_DURATION, FRIENDLY_NAME)) {
    lastUpdateTime = millis();
  }
  Serial.println();

  tinyUPnP->printAllPortMappings();
  Serial.println();


```
**program stalls here**
port mapping works because I can see it on my routers UPnP page, but it never reaches my loop function.  Just keeps printing SSDS info, which I assume is from the `printAllPortMappings()` function.
```
  Serial.println("UPnP done");

}

void loop(void) {


  // update UPnP port mapping rule if needed
  if ((millis() - lastUpdateTime) > (long) (0.8D * (double) (LEASE_DURATION * 1000.0))) {
    Serial.print("UPnP rule is about to be revoked, renewing lease");
    if (tinyUPnP->addPortMapping(WiFi.localIP(), LISTEN_PORT, RULE_PROTOCOL_TCP, LEASE_DURATION, FRIENDLY_NAME)) {
      lastUpdateTime = millis();
    }
  }
}
 ```

**Comment by ofekp** [comment] 2018-06-21 20:52
Please make sure to use the `newApi` branch.
It is updated after I merged the branch `issue10` with the `UDP_TX_PACKET_MAX_SIZE` issue.
It also solves what you described here. `printAllPortMappings` takes a long time if you have many UPnP ports open on your IGD router. The new branch will only print this if you encounter an error upon startup.
If you prefer to use your current code you can simply delete this method from the `.ino` file.
I do recommend using the `newApi` branch, though.

**Comment by ofekp** [comment] 2018-07-20 22:09
Closing this, since the issue is resolved.
I will debug the branch `newApi` a bit more before I'll put it in master.

**Closed by ofekp** 2018-07-20 22:09 UTC
