### ISSUE TITLE
TCP connection timeout while connecting to the IDG

### ISSUE THREAD

**Issue by Ponkabonk** [ofekp/TinyUPnP#3] opened 2017-10-23 21:45 UTC
I'm using a Verizon/Frontier Fios router.  Every few seconds, I see the message "TCP connection timeout while connecting to the IDG".  From the logs, you'll see that it correctly found the IDG.  I have also included the output from rootDesc.xml.  I think it is supposed to contain the string defined by UPNP_SERVICE_TYPE (urn:schemas-upnp-org:service:WANPPPConnection:1) which is not in rootDesc.xml.  That's just a guess though.

Just in case it is working but doesn't appear to, I turned off WiFi on my phone and tried to connect to the device anyway.  No joy.
[serial_logs.txt](https://github.com/ofekp/TinyUPnP/files/1408870/serial_logs.txt)
[rootDesc.txt](https://github.com/ofekp/TinyUPnP/files/1408872/rootDesc.txt)

**Comment by ofekp** [comment] 2017-10-24 16:01
I think you're right,
Please try the following branch:
https://github.com/ofekp/TinyUPnP/pull/4

**Comment by ofekp** [comment] 2017-10-24 16:16
Thanks for the details,
As you can see from the Serial log
```
IGD location found [http://192.168.1.1:41708/rootDesc.xml]
192.168.1.1
41708
/rootDesc.xml
Connected to IGD
<service>
</service>
TCP connection timeout while connecting to the IGD
TCP connection timeout while connecting to the IGD
```
The connection to the router established

**Comment by Ponkabonk** [comment] 2017-10-24 16:27
This comment may end up being duplicated.

I couldn’t figure out how to pull the new branch so I just edited those two lines directly in the .cpp and .h files.  There was no change.  I added a debugPrint to the .cpp file to verify that it is being used to compile the code.  It is.

The symptoms are the same as described earlier.

To test to verify non-functionality, I turn off WiFi on my phone so I'm sure to be connected to my outside network.  Then I use the following (with my LISTEN_PORT set to 64352) http://<my IPChicken Address>:64352

**Comment by Ponkabonk** [comment] 2017-10-24 16:28
Hi Ofek,

 

I couldn’t figure out how to pull the new branch (sorry, new at this) so I just edited those two lines directly in the .cpp and .h files.  There was no change.  I added a debugPrint to the .cpp file to verify that it is being used to compile the code.  It is.

 

The symptoms are the same as described earlier.

 

-Mike

**Comment by ofekp** [comment] 2017-10-24 17:01
Please attach the xml files that result from the following queries:
1) http://192.168.1.1:41708/L3F.xml
2) http://192.168.1.1:41708/WANIPCn.xml

I need to know if they work and their output please.

**Comment by Ponkabonk** [comment] 2017-10-24 17:10
Here you go.

[L3F.txt](https://github.com/ofekp/TinyUPnP/files/1411750/L3F.txt)

[WANIPCn.txt](https://github.com/ofekp/TinyUPnP/files/1411748/WANIPCn.txt)

**Comment by ofekp** [comment] 2017-10-24 17:24
Cool, looks like what we need is WANIPCn.txt,
I think it cannot find it because in the first file you attached there is no BaseURL tag.
I just need to make it get the ip and port from the LOCATION that was found and then it should find the file. Let me change the code a bit, this time it will be more than two lines, so you will have to go to the branch --> changed files --> press "view" and copy the whole text into your Arduino library.

**Comment by ofekp** [comment] 2017-10-24 17:49
funny, it was two line after all :)
I am not sure it will solve it, the URLBase change I made, but you would have run into this issue anyway.
I added few log lines that I would love to see.
please try the branch again, follow the changes or copy paste it after "view"ing the file, there's a "view" button there:
https://github.com/ofekp/TinyUPnP/pull/4/files
In addition, I would suggest increasing TCP_CONNECTION_TIMEOUT_MS from 6000 to 12000.

**Comment by Ponkabonk** [comment] 2017-10-24 17:57
No change.  Well, it did get slower but that's because I set TCP_CONNECTION_TIMEOUT_MS to 12000 as suggested.  :o)

I copied and pasted the entirety of the .cpp file so I'm working off the exact same code as in the repository.
[Logs2.txt](https://github.com/ofekp/TinyUPnP/files/1411895/Logs2.txt)

**Comment by ofekp** [comment] 2017-10-24 18:04
Ho, I see something.

Please try to replace all occurrences of
`_wifiClient.readStringUntil('\r');`
with
`_wifiClient.readStringUntil('\n');`

**Comment by Ponkabonk** [comment] 2017-10-24 18:11
Replaced 4 occurrences.  No change.
[Logs3.txt](https://github.com/ofekp/TinyUPnP/files/1411936/Logs3.txt)

**Comment by ofekp** [comment] 2017-10-24 18:18
I think the problem is that the xml that is printed should have been printed in multiple lines rather than a single long line. 
You sent me the file `rootDesc.txt` before, was it add to GitHub as-is, I mean the same way it was retrieved from the router? because it shows new-lines when I opened it, yet the `readStringUntil` is not recognizing this new-line, this is why the whole thing is printed in a single line...
BTW, there are 4 occurrences, please verify.

**Comment by Ponkabonk** [comment] 2017-10-24 18:28
4 occurrences confirmed.

I've attached two files.  One shows what it looks like when I view page source.  For the other, I copy-pasted the page source into a .txt file using Notepad++.
![rootdesc](https://user-images.githubusercontent.com/4604965/31960985-4c9e3cba-b8ae-11e7-919c-0861d058c765.PNG)
[rootDesc2.txt](https://github.com/ofekp/TinyUPnP/files/1412002/rootDesc2.txt)

When I provided the file the first time, I did not copy the page source.  Instead, I copied it from the browser display.  I suspect that added the line feeds.

**Comment by ofekp** [comment] 2017-10-24 19:00
OK that is very helpful,
Let me see how I can change the code in a way that will answer this case

**Comment by ofekp** [comment] 2017-10-24 19:09
Can you please try the code now? I added a header to the request:
_wifiClient.println("Content-Type: text/xml; charset=\"utf-8\"");

I really hope it will add those new-lines. Fingers crossed!

**Comment by Ponkabonk** [comment] 2017-10-24 19:38
I copied over both the .h and .cpp files to make sure I have all of your changes.  Then, I set the timeout to 12000ms again.  I'm still seeing the timeout error.  Logs attached.
[Logs4.txt](https://github.com/ofekp/TinyUPnP/files/1412254/Logs4.txt)

**Comment by ofekp** [comment] 2017-10-24 20:13
@Ponkabonk if the previous solution does not work, please have a go at this:
https://github.com/ofekp/TinyUPnP/pull/6
Better copy paste the entire code

**Comment by Ponkabonk** [comment] 2017-10-24 20:51
I used the verizonFrontier2 branch.  No noticeable difference.  Logs attached.
[Logs5.txt](https://github.com/ofekp/TinyUPnP/files/1412466/Logs5.txt)

**Comment by ofekp** [comment] 2017-10-24 21:27
Weird.. I will have to devise a test that will take the non formatted xml and will apply the code on it so that I will be able to check it. I will continue tomorrow. Thank you for the flawless cooperation :) this is very helpful.

**Comment by ofekp** [comment] 2017-10-25 17:47
I just checked the new code on my LEDs (though my router splits the XML to separated line)
It had a compilation error which I fixed just now inside the branch (int declaration was missing).
This tells me that you may have accidentally used a different code base when compiling, can you please verify? You can add a log line that you would recognize, or add a compilation error on purpose to see if the Arduino IDE (or whatever env you're using) is failing.

**Comment by Ponkabonk** [comment] 2017-10-25 17:51
You want me to use verisonFrontier2, right?

**Comment by ofekp** [comment] 2017-10-25 17:52
Yeah, correct

**Comment by Ponkabonk** [comment] 2017-10-25 18:03
Well, actually, I found and fixed the missing int declaration yesterday but forgot to mention it to you.  I just copied over both the .cpp and .h from verizonFrontier2 and changed the message to read "Mikey is connected to the IDG".  You'll see it in the attached logs.
[Logs6.txt](https://github.com/ofekp/TinyUPnP/files/1415670/Logs6.txt)

**Comment by ofekp** [comment] 2017-10-25 18:06
Roger that,
Let me see if I can reproduce that single line XML with my setup.

**Comment by ofekp** [comment] 2017-10-25 18:33
Was able to reproduce the bug using the log you have provided,
Working to see how to fix it.
Mean time, please try one more time to change:
_wifiClient.readStringUntil('\r');
with
_wifiClient.readStringUntil('\n');
like we did last time, but with the new branch verisonFrontier2. replace all instances please.

**Comment by Ponkabonk** [comment] 2017-10-25 18:52
I replaced three instances.  Yesterday there were 4.  No change.  

FYI, my Serial Monitor is set to "Newline" (the default).  I suspect we should have ours set the same so we're looking at the same thing.  

[Logs7.txt](https://github.com/ofekp/TinyUPnP/files/1415791/Logs7.txt)

**Comment by ofekp** [comment] 2017-10-25 19:03
OK OK OK please try verisonFrontier2 again, copy paste the whole thing.

**Comment by ofekp** [comment] 2017-10-25 19:27
@Ponkabonk Please try the new code 🙏

**Comment by ofekp** [comment] 2017-10-25 19:50
Also, I agree with what you said:
> FYI, my Serial Monitor is set to "Newline" (the default). I suspect we should have ours set the same so we're looking at the same thing.

Mine is Both NL & CR, please change to that

**Comment by Ponkabonk** [comment] 2017-10-25 20:10
Success!  I disabled WiFi on my phone and was able to connect to the Web server running on the 8266 via the cell network.
  
[Logs8.txt](https://github.com/ofekp/TinyUPnP/files/1415998/Logs8.txt)

How long do you think the UPnP process should take?  There are a couple places where it stalls for a bit and then continues.

**Comment by ofekp** [comment] 2017-10-25 20:17
![](https://media.giphy.com/media/l3q2Z6S6n38zjPswo/giphy.gif)

The delay is mostly the printing of the rules, each rule is taken by a single query to the router, not the most efficient thing ever, but it is there to make sure the rule is created.
You can disable the line where it happens, it is in the `ino` example file, the line you're looking for is:
`tinyUPnP->printAllPortMappings();`

**Comment by Ponkabonk** [comment] 2017-10-25 20:24
Nice work!  Thanks for the effort.  I'll connect this to my project next.  Your example is pretty straightforward so I don't anticipate any problem.  Shall we move on to my request for automatically selecting the port?

**Comment by ofekp** [comment] 2017-10-25 20:46
You too, thanks for being quick with responding to my questions :) Was glad help.
We may, see you there, though, I must warn, I may postpone that feature unless more people will be interested. The package is intended to be slim. Anyone that is interested in that can actually use my package to scan the current port mappings with only minor changes and transmit the port to their server, though as I will suggest this may not be the best practice.
Closing this this issue and merging.
Thanks again!

**Closed by ofekp** 2017-10-25 20:46 UTC
